### ISSUE TITLE
Checkins are pushed with incorrect order when more than one is new

### ISSUE THREAD

**Issue by kriben** [kriben/untappdtoirc#1]
Steps to reproduce:
1. Check in two beers between the api polls.
2. Watch it in irc

Expected results:
- Beers are printed to irc in the order they are checked in.

Actual results:
- The newest beer is printed first.

(cc: @atlefren)

**Comment by mdlayher** [comment]
Hi there!  The Untappd API endpoint which returns user checkins will indeed always report the newest checkin first.  Since it does not seem to provide its own sort parameter, you could implement `sort.Interface` using a custom type to achieve the result you want:

``` go
// byCheckinTime implements sort.Interface for []*untappd.Checkin.
type byCheckinTime []*untappd.Checkin

func (b byCheckinTime) Len() int               { return len(b) }
func (b byCheckinTime) Less(i int, j int) bool { return b[i].Created.Before(b[j].Created) }
func (b byCheckinTime) Swap(i int, j int)      { b[i], b[j] = b[j], b[i] }
```

Invoking it is simple: `sort.Sort(byCheckinTime(checkins))`.

**Comment by kriben** [comment]
@mdlayher Good idea. My initial thought was to just reverse the list (or iterate backwards over it), but this looks better.

**Comment by kriben** [comment]
Fixed using suggestion from @mdlayher
